# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-15 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript', models.TextField(max_length=100000)),
                ('encrypted_phone', models.TextField(max_length=200)),
                ('approved', models.BooleanField(default=False)),
                ('phone_number', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
