# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('single_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('transcript', models.TextField(max_length=100000)),
                ('encrypted_phone', models.TextField(max_length=200, primary_key=True, serialize=False)),
                ('approved', models.BooleanField(default=False)),
                ('phone_number', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Request',
        ),
    ]
